name: Cmake build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup cmake
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          gcc --version
          cmake --version
          ninja --version
      - name: Setup Valgrind
        run: |
          sudo apt-get install valgrind
          pip install ValgrindCI
          valgrind --version
#      - name: Setup SDL
#        run: |
#          sudo apt-get install libsdl2-dev libsdl2-image-dev
#          sudo mkdir /usr/lib/x86_64-linux-gnu/cmake/sdl2_image/
#          echo -e 'set(prefix "/usr")\nset(exec_prefix "${prefix}")\nset(libdir "${prefix}/lib/x86_64-linux-gnu")\nset(SDL2_IMAGE_PREFIX "/usr")\nset(SDL2_IMAGE_EXEC_PREFIX "/usr")\nset(SDL2_IMAGE_INCLUDE_DIRS "${prefix}/include/SDL2_image")\nset(SDL2_IMAGE_LIBRARIES "-lSDL2_image")' > sdl2_image-config.cmake
#          sudo mv sdl2_image-config.cmake /usr/lib/x86_64-linux-gnu/cmake/sdl2_image/
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache build files
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build
          key: ${{ runner.OS }}-build-cache
      - name: Set warnings as errors for CI
        run: echo -e "set(CMAKE_COMPILE_WARNING_AS_ERROR true)\n$(cat CMakeLists.txt)" > CMakeLists.txt
      - name: Setup project build system
        run: cmake -S . -B build -Werror=dev
      - name: Build
        run: cmake --build build -j
      - name: Tests
        working-directory: ./build/test/
        run: valgrind --tool=memcheck --xml=yes --xml-file=unit_tests_valgrind.xml --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./engine-tests --gtest_filter="*" --gtest_color=no
      - name: Valgrind
        working-directory: ./build/test/
        run: |
          valgrind-ci unit_tests_valgrind.xml --summary
          valgrind-ci unit_tests_valgrind.xml --abort-on-errors